import { TMockGames } from "../types"

export const mostPopularGames: TMockGames[] = [
  {
    id: 998,
    title: "Factorio (demo)",
    poster_src: "/assets/img/factorio-cover.webp",
    availableDevice: ["keyboard"],
  },
  {
    id: 997,
    title: "Minecraft",
    poster_src: "/assets/img/minecraft.webp",
    availableDevice: ["keyboard"],
  },
  {
    id: 999,
    title: "Factorio",
    poster_src: "/assets/img/factorio-cover.webp",
    availableDevice: ["keyboard"],
  },
  {
    id: 1,
    title: "Hogwarts Legacy",
    poster_src: "/assets/img/cover_game_item_1.webp",
    availableDevice: ["keyboard"],
  },
  {
    id: 2,
    title: "Phasmophobia",
    poster_src: "/assets/img/cover_game_item_2.webp",
    availableDevice: ["keyboard"],
  },
  {
    id: 3,
    title: "Left 4 Dead 2",
    poster_src: "/assets/img/cover_game_item_3.webp",
    availableDevice: ["touch"],
  },
  {
    id: 4,
    title: "Hogwarts Legacy",
    poster_src: "/assets/img/cover_game_item_1.webp",
    availableDevice: ["keyboard"],
  },
  {
    id: 5,
    title: "Phasmophobia",
    poster_src: "/assets/img/cover_game_item_2.webp",
    availableDevice: ["keyboard"],
  },
  {
    id: 6,
    title: "Left 4 Dead 2",
    poster_src: "/assets/img/cover_game_item_3.webp",
    availableDevice: ["touch"],
  },
  {
    id: 7,
    title: "Hogwarts Legacy",
    poster_src: "/assets/img/cover_game_item_1.webp",
    availableDevice: ["keyboard"],
  },
  {
    id: 8,
    title: "Phasmophobia",
    poster_src: "/assets/img/cover_game_item_2.webp",
    availableDevice: ["keyboard"],
  },
  {
    id: 9,
    title: "Left 4 Dead 2",
    poster_src: "/assets/img/cover_game_item_3.webp",
    availableDevice: ["touch"],
  },
]

export const newlyAddedGames: TMockGames[] = [
  {
    id: 1,
    title: "BigFoot",
    poster_src: "/assets/img/cover_game_item_4.webp",
    availableDevice: ["keyboard"],
  },
  {
    id: 2,
    title: "Shop Titans",
    poster_src: "/assets/img/cover_game_item_5.webp",
    availableDevice: ["keyboard"],
  },
  {
    id: 3,
    title: "Half-Life: Alyx",
    poster_src: "/assets/img/cover_game_item_6.webp",
    availableDevice: ["touch"],
  },
  {
    id: 4,
    title: "BigFoot",
    poster_src: "/assets/img/cover_game_item_4.webp",
    availableDevice: ["keyboard"],
  },
  {
    id: 5,
    title: "Shop Titans",
    poster_src: "/assets/img/cover_game_item_5.webp",
    availableDevice: ["keyboard"],
  },
  {
    id: 6,
    title: "Half-Life: Alyx",
    poster_src: "/assets/img/cover_game_item_6.webp",
    availableDevice: ["touch"],
  },
  {
    id: 7,
    title: "BigFoot",
    poster_src: "/assets/img/cover_game_item_4.webp",
    availableDevice: ["keyboard"],
  },
  {
    id: 8,
    title: "Shop Titans",
    poster_src: "/assets/img/cover_game_item_5.webp",
    availableDevice: ["keyboard"],
  },
  {
    id: 9,
    title: "Half-Life: Alyx",
    poster_src: "/assets/img/cover_game_item_6.webp",
    availableDevice: ["touch"],
  },
  {
    id: 10,
    title: "BigFoot",
    poster_src: "/assets/img/cover_game_item_4.webp",
    availableDevice: ["keyboard"],
  },
  {
    id: 11,
    title: "Shop Titans",
    poster_src: "/assets/img/cover_game_item_5.webp",
    availableDevice: ["keyboard"],
  },
  {
    id: 12,
    title: "Half-Life: Alyx",
    poster_src: "/assets/img/cover_game_item_6.webp",
    availableDevice: ["touch"],
  },
]

export const immediatelyAvailableGames: TMockGames[] = [
  {
    id: 1,
    title: "BigFoot",
    poster_src: "/assets/img/cover_game_item_1.webp",
    availableDevice: ["keyboard"],
  },
  {
    id: 2,
    title: "Shop Titans",
    poster_src: "/assets/img/cover_game_item_2.webp",
    availableDevice: ["keyboard"],
  },
  {
    id: 3,
    title: "Half-Life: Alyx",
    poster_src: "/assets/img/cover_game_item_3.webp",
    availableDevice: ["touch"],
  },
  {
    id: 4,
    title: "BigFoot",
    poster_src: "/assets/img/cover_game_item_4.webp",
    availableDevice: ["keyboard"],
  },
  {
    id: 5,
    title: "Shop Titans",
    poster_src: "/assets/img/cover_game_item_5.webp",
    availableDevice: ["keyboard"],
  },
  {
    id: 6,
    title: "Half-Life: Alyx",
    poster_src: "/assets/img/cover_game_item_6.webp",
    availableDevice: ["touch"],
  },
  {
    id: 7,
    title: "BigFoot",
    poster_src: "/assets/img/cover_game_item_2.webp",
    availableDevice: ["keyboard"],
  },
  {
    id: 8,
    title: "Shop Titans",
    poster_src: "/assets/img/cover_game_item_6.webp",
    availableDevice: ["keyboard"],
  },
  {
    id: 9,
    title: "Half-Life: Alyx",
    poster_src: "/assets/img/cover_game_item_1.webp",
    availableDevice: ["touch"],
  },
  {
    id: 10,
    title: "Hogwarts Legacy",
    poster_src: "/assets/img/cover_game_item_3.webp",
    availableDevice: ["keyboard"],
  },
  {
    id: 11,
    title: "Phasmophobia",
    poster_src: "/assets/img/cover_game_item_5.webp",
    availableDevice: ["keyboard"],
  },
  {
    id: 12,
    title: "Left 4 Dead 2",
    poster_src: "/assets/img/cover_game_item_2.webp",
    availableDevice: ["touch"],
  },
]

export const recentlyPlayedGames: TMockGames[] = [
  {
    id: 1,
    title: "Baldur`s Gate 3",
    poster_src: "/assets/img/cover_game_big_item_1.webp",
    availableDevice: ["keyboard"],
    lastPlayData: "11/28/2023",
  },
  {
    id: 2,
    title: "Hogwarts Legacy",
    poster_src: "/assets/img/cover_game_big_item_2.webp",
    availableDevice: ["keyboard"],
    lastPlayData: "11/28/2023",
  },
  {
    id: 3,
    title: "Baldur`s Gate 3",
    poster_src: "/assets/img/cover_game_big_item_1.webp",
    availableDevice: ["keyboard"],
    lastPlayData: "11/28/2023",
  },
  {
    id: 4,
    title: "Hogwarts Legacy",
    poster_src: "/assets/img/cover_game_big_item_2.webp",
    availableDevice: ["keyboard"],
    lastPlayData: "11/28/2023",
  },
  {
    id: 5,
    title: "Baldur`s Gate 3",
    poster_src: "/assets/img/cover_game_big_item_1.webp",
    availableDevice: ["keyboard"],
    lastPlayData: "11/28/2023",
  },
  {
    id: 6,
    title: "Hogwarts Legacy",
    poster_src: "/assets/img/cover_game_big_item_2.webp",
    availableDevice: ["keyboard"],
    lastPlayData: "11/28/2023",
  },
  {
    id: 7,
    title: "Baldur`s Gate 3",
    poster_src: "/assets/img/cover_game_big_item_1.webp",
    availableDevice: ["keyboard"],
    lastPlayData: "11/28/2023",
  },
  {
    id: 8,
    title: "Hogwarts Legacy",
    poster_src: "/assets/img/cover_game_big_item_2.webp",
    availableDevice: ["keyboard"],
    lastPlayData: "11/28/2023",
  },
  {
    id: 9,
    title: "Baldur`s Gate 3",
    poster_src: "/assets/img/cover_game_big_item_1.webp",
    availableDevice: ["keyboard"],
    lastPlayData: "11/28/2023",
  },
  {
    id: 10,
    title: "Hogwarts Legacy",
    poster_src: "/assets/img/cover_game_big_item_2.webp",
    availableDevice: ["keyboard"],
    lastPlayData: "11/28/2023",
  },
  {
    id: 11,
    title: "Baldur`s Gate 3",
    poster_src: "/assets/img/cover_game_big_item_1.webp",
    availableDevice: ["keyboard"],
    lastPlayData: "11/28/2023",
  },
  {
    id: 12,
    title: "Hogwarts Legacy",
    poster_src: "/assets/img/cover_game_big_item_2.webp",
    availableDevice: ["keyboard"],
    lastPlayData: "11/28/2023",
  },
]
