import { Chakra_Petch } from "next/font/google"

import { ToastContainer } from "react-toastify"
import "react-toastify/dist/ReactToastify.min.css"

import StoreProvider from "@/core/StoreProvider"

import { Layout } from "@/views/Layout"

import "@/shared/styles/main.scss"

export const metadata = {
  title: "BorgGames",
  description: "Generated by Next.js",
}

const chakra_petch = Chakra_Petch({
  weight: ["400", "500", "600", "700"],
  style: ["normal"],
  subsets: ["latin"],
  display: "swap",
})

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={chakra_petch.className}>
      <head>
        <link rel="shortcut icon" href="/assets/fav.png" type="image/x-icon" />
      </head>
      <body>
        <StoreProvider>
          <Layout>
            {children}
            <ToastContainer
              position="top-right"
              autoClose={2000}
              hideProgressBar={false}
              newestOnTop={false}
              closeOnClick
              rtl={false}
              pauseOnFocusLoss
              draggable
              pauseOnHover
              theme="colored"
            />
          </Layout>
        </StoreProvider>
      </body>
    </html>
  )
}
